//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisfacaoCast.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOTO
    {
        public int Id { get; set; }
        public int IdTipoVoto { get; set; }
        public Nullable<System.DateTime> Data_Voto { get; set; }
    
        public virtual TIPOVOTO TIPOVOTO { get; set; }
    }
}
